export const tableHead = [
  { name: 'S.No', uid: 'sno' },

  { name: 'Name', uid: 'f_name', sortable: true },
  { name: 'Email', uid: 'f_email', sortable: true },
  { name: 'Mobile No', uid: 'f_mobile' },
  { name: 'Role', uid: 'f_role' },
  { name: 'Department', uid: 'f_department' },
  { name: 'Date of Birth', uid: 'f_dob' },
  { name: 'Date of Joining', uid: 'f_doj' },
  { name: 'Description', uid: 'f_description' },

  { name: 'Action', uid: 'action' },
];
export const tableBody = [
  {
    sno: 1,
    f_id: 'ABC001',
    f_Name: 'John Doe',
    f_Email: 'john.doe@example.com',
    f_Mobile: '123-456-7890',
    f_Designation: 'Software Engineer',
    f_Gender: 'Male',
    f_Course: 'Computer Science',
    f_Date: '2024-03-03',
  },
  {
    sno: 2,
    f_id: 'ABC002',
    f_Name: 'Jane Smith',
    f_Email: 'jane.smith@example.com',
    f_Mobile: '987-654-3210',
    f_Designation: 'Web Developer',
    f_Gender: 'Female',
    f_Course: 'Information Technology',
    f_Date: '2024-03-03',
  },
  {
    sno: 3,
    f_id: 'ABC003',
    f_Name: 'Bob Johnson',
    f_Email: 'bob.johnson@example.com',
    f_Mobile: '555-123-7890',
    f_Designation: 'Network Engineer',
    f_Gender: 'Male',
    f_Course: 'Networking',
    f_Date: '2024-03-03',
  },
  {
    sno: 4,
    f_id: 'ABC004',
    f_Name: 'Alice Williams',
    f_Email: 'alice.williams@example.com',
    f_Mobile: '333-888-5555',
    f_Designation: 'Database Administrator',
    f_Gender: 'Female',
    f_Course: 'Database Management',
    f_Date: '2024-03-03',
  },
  {
    sno: 5,
    f_id: 'ABC005',
    f_Name: 'Charlie Brown',
    f_Email: 'charlie.brown@example.com',
    f_Mobile: '777-222-9999',
    f_Designation: 'Frontend Developer',
    f_Gender: 'Male',
    f_Course: 'Web Development',
    f_Date: '2024-03-03',
  },
  {
    sno: 6,
    f_id: 'ABC006',
    f_Name: 'Eva Green',
    f_Email: 'eva.green@example.com',
    f_Mobile: '111-666-4444',
    f_Designation: 'UX Designer',
    f_Gender: 'Female',
    f_Course: 'User Experience Design',
    f_Date: '2024-03-03',
  },
  {
    sno: 7,
    f_id: 'ABC007',
    f_Name: 'David Lee',
    f_Email: 'david.lee@example.com',
    f_Mobile: '999-444-7777',
    f_Designation: 'DevOps Engineer',
    f_Gender: 'Male',
    f_Course: 'DevOps',
    f_Date: '2024-03-03',
  },
  {
    sno: 8,
    f_id: 'ABC008',
    f_Name: 'Fiona White',
    f_Email: 'fiona.white@example.com',
    f_Mobile: '666-333-1111',
    f_Designation: 'Full Stack Developer',
    f_Gender: 'Female',
    f_Course: 'Software Engineering',
    f_Date: '2024-03-03',
  },
  {
    sno: 9,
    f_id: 'ABC009',
    f_Name: 'George Brown',
    f_Email: 'george.brown@example.com',
    f_Mobile: '222-777-8888',
    f_Designation: 'System Analyst',
    f_Gender: 'Male',
    f_Course: 'Systems Analysis',
    f_Date: '2024-03-03',
  },
  {
    sno: 10,
    f_id: 'ABC010',
    f_Name: 'Helen Miller',
    f_Email: 'helen.miller@example.com',
    f_Mobile: '888-555-3333',
    f_Designation: 'Cybersecurity Analyst',
    f_Gender: 'Female',
    f_Course: 'Cybersecurity',
    f_Date: '2024-03-03',
  },
  {
    sno: 11,
    f_id: 'ABC011',
    f_Name: 'Ivan Perez',
    f_Email: 'ivan.perez@example.com',
    f_Mobile: '444-999-2222',
    f_Designation: 'Machine Learning Engineer',
    f_Gender: 'Male',
    f_Course: 'Machine Learning',
    f_Date: '2024-03-03',
  },
  {
    sno: 12,
    f_id: 'ABC012',
    f_Name: 'Jessica Taylor',
    f_Email: 'jessica.taylor@example.com',
    f_Mobile: '777-111-5555',
    f_Designation: 'Data Analyst',
    f_Gender: 'Female',
    f_Course: 'Data Analysis',
    f_Date: '2024-03-03',
  },
  {
    sno: 13,
    f_id: 'ABC013',
    f_Name: 'Kevin Clark',
    f_Email: 'kevin.clark@example.com',
    f_Mobile: '333-555-7777',
    f_Designation: 'UI Developer',
    f_Gender: 'Male',
    f_Course: 'UI/UX Design',
    f_Date: '2024-03-03',
  },
  {
    sno: 14,
    f_id: 'ABC014',
    f_Name: 'Lily Garcia',
    f_Email: 'lily.garcia@example.com',
    f_Mobile: '111-777-9999',
    f_Designation: 'Project Manager',
    f_Gender: 'Female',
    f_Course: 'Project Management',
    f_Date: '2024-03-03',
  },
  {
    sno: 15,
    f_id: 'ABC015',
    f_Name: 'Mike Davis',
    f_Email: 'mike.davis@example.com',
    f_Mobile: '999-333-8888',
    f_Designation: 'IT Consultant',
    f_Gender: 'Male',
    f_Course: 'IT Consulting',
    f_Date: '2024-03-03',
  },
  {
    sno: 16,
    f_id: 'ABC016',
    f_Name: 'Nina Turner',
    f_Email: 'nina.turner@example.com',
    f_Mobile: '555-888-1111',
    f_Designation: 'Back-end Developer',
    f_Gender: 'Female',
    f_Course: 'Backend Development',
    f_Date: '2024-03-03',
  },
  {
    sno: 17,
    f_id: 'ABC017',
    f_Name: 'Oscar Martinez',
    f_Email: 'oscar.martinez@example.com',
    f_Mobile: '222-999-4444',
    f_Designation: 'Quality Assurance Engineer',
    f_Gender: 'Male',
    f_Course: 'QA Testing',
    f_Date: '2024-03-03',
  },
];
